In [21]:
from hrm_sdk import HRMInferenceClient

client = HRMInferenceClient("http://localhost:8000")
result = client.infer([0, 1, 2, 3])

print(result.predictions)

[31, 22, 9, 12, 10, 8, 18, 8, 19, 11, 22, 26, 8, 22, 9, 12, 10, 20, 14, 18, 17, 15, 8, 18, 11, 22, 26, 8, 22, 9, 16, 17, 15, 14, 21, 8, 19, 11, 22, 32, 12, 22, 9, 12, 10, 17, 24, 8, 19, 11, 22, 8, 11, 8, 22, 9, 31, 22, 9, 12, 10, 8, 18, 8, 19, 11, 22, 26, 8, 31, 22, 9, 12, 10, 8, 21, 8, 24, 11, 22, 26, 8, 22, 9, 12, 10, 20, 14, 18, 17, 11, 22, 18, 8, 22, 22, 8, 12, 9, 20, 31, 22, 9, 12, 10, 8, 18, 31, 8, 11, 22, 26, 31, 31, 22, 9, 12, 10, 8, 18, 8, 24, 11, 22, 26, 8, 22, 9, 12, 10, 20, 14, 21, 17, 11, 8, 18, 8, 22, 22, 16, 17, 9, 9, 18, 8, 9, 11, 8, 8, 11, 22, 8, 11, 22, 26, 31, 31, 22, 9, 12, 10, 8, 14, 8, 19, 11, 22, 18, 31, 22, 9, 12, 10, 9, 31, 8, 8, 24, 8, 26, 8, 22, 22, 9, 12, 9, 20, 21, 8, 19, 11, 8, 26, 8, 22, 19, 12, 8, 26, 31, 31, 22, 16, 12, 8, 8, 18, 8, 19, 11, 22, 26, 31, 22, 9, 12, 17, 8, 14, 21, 8, 11, 8, 18, 26, 22, 22, 9, 12, 10, 8, 24, 8, 19, 11, 22, 26, 8, 22, 9, 12, 17, 20, 31, 31, 8, 11, 12, 8, 8, 14, 8, 19, 11, 8, 31, 31, 22, 9, 12, 10, 8, 8, 21, 8, 24, 8, 22, 31,

In [22]:
import numpy as np


data = np.load("data/questbench-planning/test/all__inputs.npy")
labels = np.load("data/questbench-planning/test/all__labels.npy")

In [23]:
data[0]

array([ 2,  9, 12, ...,  0,  0,  0], shape=(1007,))

In [24]:
result = client.infer(data[200])
print(result.predictions)

[31, 22, 35, 12, 8, 36, 37, 15, 33, 20, 30, 12, 10, 33, 8, 10, 15, 15, 19, 15, 19, 34, 22, 32, 32, 22, 22, 8, 22, 15, 8, 15, 8, 19, 22, 8, 16, 8, 22, 32, 22, 22, 8, 22, 9, 12, 10, 8, 16, 8, 14, 32, 22, 32, 8, 14, 8, 12, 12, 10, 8, 8, 14, 22, 22, 12, 10, 8, 16, 8, 15, 11, 22, 26, 8, 22, 9, 12, 10, 8, 14, 8, 15, 11, 22, 26, 8, 22, 9, 12, 10, 8, 18, 8, 15, 11, 22, 32, 8, 22, 9, 12, 10, 8, 16, 8, 19, 11, 22, 15, 8, 22, 9, 15, 12, 8, 8, 8, 19, 19, 33, 14, 15, 22, 15, 15, 15, 15, 22, 32, 32, 11, 22, 8, 8, 9, 9, 19, 37, 37, 22, 8, 9, 15, 19, 12, 8, 8, 8, 15, 37, 19, 22, 32, 32, 15, 19, 15, 8, 9, 9, 8, 14, 19, 22, 32, 32, 9, 15, 16, 8, 8, 16, 8, 19, 19, 22, 33, 33, 22, 8, 19, 19, 19, 26, 8, 8, 8, 15, 33, 33, 33, 33, 15, 18, 33, 33, 34, 33, 15, 15, 15, 8, 33, 22, 16, 16, 15, 33, 33, 15, 15, 15, 16, 8, 8, 8, 9, 19, 19, 19, 33, 8, 33, 8, 8, 8, 16, 16, 8, 15, 19, 19, 33, 8, 15, 22, 15, 19, 19, 15, 16, 8, 15, 19, 22, 8, 8, 8, 8, 24, 37, 15, 33, 18, 15, 34, 32, 15, 8, 9, 9, 24, 8, 15, 33, 33, 33, 15

In [26]:
labels[200]

array([31, 22, 35, ...,  0,  0,  0], shape=(1007,))

In [25]:
labels[200] == result.predictions

array([ True,  True,  True, ..., False, False, False], shape=(1007,))

In [43]:
import numpy as np
import tqdm
import itertools


total_accuracy = 0
exact_accuracy = 0
pad_id = 0
divisor = 0

for X, y in tqdm.tqdm(itertools.islice(zip(data, labels), 100)):
    y = np.array(y)
    mask = y != pad_id

    y_pred = np.array(client.infer(X).predictions)

    valid_y = y[mask]
    valid_pred = y_pred[mask]

    accuracy = np.mean(valid_y == valid_pred) if len(valid_y) > 0 else 0.0

    exact = np.all(valid_y == valid_pred) if len(valid_y) > 0 else False

    total_accuracy += accuracy
    exact_accuracy += int(exact)
    divisor += 1

total_accuracy = total_accuracy / divisor
exact_accuracy = exact_accuracy / divisor


print(f"{total_accuracy = }")
print(f"{exact_accuracy = }")

100it [02:42,  1.63s/it]

total_accuracy = np.float64(0.8998622826316036)
exact_accuracy = 0.74


np.float64(1.588877855014896e-05)

0.0